FROM pcic/geospatial-python

RUN mkdir /app
ADD requirements.txt /app
WORKDIR /app
RUN pip3 install -U pip pipenv --ignore-installed
RUN pipenv install

ADD . /app/

RUN pipenv run ./setup.py install

EXPOSE 8000
ENV FLASK_APP ce.wsgi:app
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

CMD pipenv run flask run -p 8000 -h 0.0.0.0 --no-reload
