FROM pcic/geospatial-python:3.8.4

RUN mkdir /app
ADD poetry.lock /app
ADD pyproject.toml /app
WORKDIR /app

RUN apt-get update && apt-get install -yq libffi-dev curl

COPY poetry.lock pyproject.toml /app/

ENV POETRY_HOME="/opt/poetry"
ENV PATH="${POETRY_HOME}/bin:${PATH}"

RUN curl -sSL https://install.python-poetry.org | python3 -

ADD . /app/
RUN poetry install --extras dev


EXPOSE 8000
ENV FLASK_APP=ce.wsgi:app
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

CMD ["poetry", "run", "flask", "run", "-p", "8000", "-h", "0.0.0.0", "--no-reload"]