name: Python CI

on: push

jobs:
  test:

    runs-on: ubuntu-22.04
    container: pcic/geospatial-python:3.3.0

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        apk upgrade
        apk add libxml2-dev libxslt-dev libffi-dev

    - name: Install poetry
      run: |
        wget -O - https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt

    - name: Test with pytest (full)
      if: github.ref == 'refs/heads/master'
      run: |
        poetry run py.test -m "not online" -v
    
    - name: Test with pytest (fast)
      if: github.ref != 'refs/heads/master'
      run: |
        poetry run py.test -m "not online and not slow" -v
