name: Python CI

on: push

jobs:
  test:

    runs-on: ubuntu-20.04
    container: pcic/geospatial-python:3.2.0

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apk upgrade
        apk add libxml2-dev libxslt-dev
        pip install -U pip pipenv --ignore-installed

    - id: cache-pipenv
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies if changed
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --deploy --dev --system --site-packages
        pip install .
    
    - name: Test with pytest (full)
      if: github.ref == 'refs/heads/master'
      run: |
        py.test -m "not online" -v
    
    - name: Test with pytest (fast)
      if: github.ref != 'refs/heads/master'
      run: |
        py.test -m "not online and not slow" -v
