name: Python CI

on: push

jobs:
  test:

    runs-on: ubuntu-22.04
    container: pcic/geospatial-python:python-310

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -yq libxml2-dev
        apt-get install -yq libxslt-dev
        apt-get install -yq libffi-dev
        apt-get install -yq wget

    - name: Install poetry
      run: |
        wget -O - https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Install python dependencies
      run: |
        poetry install --with=dev

    - name: Test with pytest (full)
      if: github.ref == 'refs/heads/master'
      run: |
        poetry run py.test -m "not online" -v
    
    - name: Test with pytest (fast)
      if: github.ref != 'refs/heads/master'
      run: |
        poetry run py.test -m "not online and not slow" -v
