name: Python CI

on: push

permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-24.04
    container: pcic/geospatial-python:3.8.4
    timeout-minutes: 15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    env:
      HOME: /root

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install system dependencies
        run: |
          apt-get update 
          apt-get install -yq libxml2-dev libxslt-dev libffi-dev wget pipx

      - name: Install poetry
        run: |
          pipx install "poetry==2.4.0"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install python dependencies
        run: |
          poetry install --extras dev

      - name: Test with pytest (full)
        if: github.ref == 'refs/heads/master'
        run: |
          poetry run py.test -m "not online" -v

      - name: Test with pytest (fast)
        if: github.ref != 'refs/heads/master'
        run: |
          poetry run py.test -m "not online and not slow" -v
